import NavBar from "./components/Navbar/page";
import "./globals.css";

export const metadata = {
  title: "Curling You Say",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <div className="page">{children}</div>
      </body>
    </html>
  );
}
